posix_metrics = [
    "UPS Monitoring (apcupsd)",
    "Cassandra Cluster Status (cassandra)",
    "Iptables rules count (checkiptables)",
    "PF Firewall rules count (checkpf_firewall)",
    "PID monitor (checkpid)",
    "File checksum monitor (checksum)",
    "CPU percent utilization (cpu_utilization)",
    "Disk percent utilization (disk_utilization)",
    "DNS Query (dnslookup)",
    "Disk Freespace (drives)",
    "File mtime status (fileage)",
    "HTTP Check Stats (httpcheck)",
    "Iocage jail status (iocage)",
    "IP addresses on host (ip_addrs)",
    "Free Memory monitor (memory)",
    "Memory Available monitor (memavail)",
    "MongoDB query (mongodbstat)",
    "MySQL query (mysqlstat)",
    "Bandwidth percent utilization (net_utilization)",
    "PostgreSQL query (pgsqlstat)",
    "Host ping status (pingstatus)",
    "Load averages (processor)",
    "RAM percent utilization (ram_utilization)",
    "Redis Master monitor (redismaster)",
    "Drive SMART status (smartctl)",
    "ZFS Dataset Freespace (zfs)",
    "ZPOOL status (zpool)",
]

powershell_metrics = [
    "File checksum monitor (checksum)",
    "CPU percent utilization (cpu_utilization)",
    "Load averages (cpuload)",
    "Disk percent utilization (disk_utilization)",
    "Disk Freespace (drives)",
    "File mtime status (fileage)",
    "HTTP Check Stats (httpcheck)",
    "Host IP status (ip_addrs)",
    "Free Memory monitor (memory)",
    "MongoDB query (mongodbstat)",
    "Bandwidth percent utilization (net_utilization)",
    "RAM percent utilization (ram_utilization)",
]

python_metrics = [
    "UPS Monitoring (apcupsd)",
    "PID monitor (checkpid)",
    "File checksum monitor (checksum)",
    "Disk Freespace (diskfree)",
    "DNS Query (dnslookup)",
    "File mtime status (fileage)",
    "HTTP Check Stats (httpcheck)",
    "Host IP status (ip_addrs)",
    "Load averages (load)",
    "Memory Available monitor (memavail)",
    "Free Memory monitor (memfree)",
    "MongoDB query (mongodbstat)",
    "MySQL query (mysqlstat)",
    "Host ping status (pingstatus)",
    "Redis Master monitor (redismaster)",
]
